import {lazy} from "react";

export const ErrorPage = lazy(() => import('../../pages/ErrorPage/ErrorPage').then(m => ({default: m.ErrorPage})))
export const HomePage = lazy(() => import('../../pages/HomePage/HomePage').then(m => ({default: m.HomePage})))
export const SignInPage = lazy(() => import('../../pages/SignInPage/SignInPage').then(m => ({default: m.SignInPage})))
export const CustomRequestPage = lazy(() => import('../../pages/CustomRequestPage/CustomRequestPage').then(m => ({default: m.CustomRequestPage})))
export const ChangePasswordPage = lazy(() => import('../../pages/ChangePasswordPage/ChangePasswordPage').then(m => ({default: m.ChangePasswordPage})))
export const StreetPage = lazy(() => import('../../pages/StreetPage/StreetPage').then(m => ({default: m.StreetPage})))
export const EditStreetPage = lazy(() => import('../../pages/StreetPage/edit/EditStreetPage').then(m => ({default: m.EditStreetPage})))
export const CreateStreetPage = lazy(() => import('../../pages/StreetPage/create/CreateStreetPage').then(m => ({default: m.CreateStreetPage})))
export const PostPage = lazy(() => import('../../pages/PostPage/PostPage').then(m => ({default: m.PostPage})))
export const CreatePostPage = lazy(() => import('../../pages/PostPage/CreatePostPage/CreatePostPage').then(m => ({default: m.CreatePostPage})))
export const EditPostPage = lazy(() => import('../../pages/PostPage/EditPostPage/EditPostPage').then(m => ({default: m.EditPostPage})))
export const BankPage = lazy(() => import('../../pages/BankPage/BankPage').then(m => ({default: m.BankPage})))
export const CreateBankPage = lazy(() => import('../../pages/BankPage/CreateBankPage/CreateBankPage').then(m => ({default: m.CreateBankPage})))
export const EditBankPage = lazy(() => import('../../pages/BankPage/EditBankPage/EditBankPage').then(m => ({default: m.EditBankPage})))
export const CountryPage = lazy(() => import('../../pages/CountryPage/CountryPage').then(m => ({default: m.CountryPage})))
export const CreateCountryPage = lazy(() => import('../../pages/CountryPage/CreateCountryPage/CreateCountryPage').then(m => ({default: m.CreateCountryPage})))
export const EditCountryPage = lazy(() => import('../../pages/CountryPage/EditCountryPage/EditCountryPage').then(m => ({default: m.EditCountryPage})))